---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 20 %>
:queues:
  - [event_tracker,   5]
  - [index,           4]
  - [timeline,        3]
  - [search_sync,     2]
  - [user,            2]
  - [data_cleanup,    1]
  - [default,         1]
  - [event_publisher, 1]
  - [github,          1]
  - [mailer,          1]
  - [network,         1]
  - [protip,          1]
  - [team,            1]
